//go:build ignore

// SPDX-License-Identifier: MIT

// genpdf417 parses the PDF417 codeword-to-bar-pattern table (ISO/IEC 15438
// Annex A) out of a downloaded copy of ZXing's PDF417.java, verifies it, and
// writes barcode_pdf417_tables.go. Nothing is transcribed by hand.
//
//	go run tools/genpdf417/main.go <path-to-PDF417.java> > barcode_pdf417_tables.go
package main

import (
	"fmt"
	"os"
	"regexp"
	"strconv"
	"strings"
)

func main() {
	src, err := os.ReadFile(os.Args[1])
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
	s := string(src)
	i := strings.Index(s, "CODEWORD_TABLE = {")
	j := strings.Index(s[i:], "};")
	body := s[i : i+j]
	re := regexp.MustCompile(`0x[0-9a-fA-F]+`)
	var vals []uint32
	for _, m := range re.FindAllString(body, -1) {
		v, _ := strconv.ParseUint(m[2:], 16, 32)
		vals = append(vals, uint32(v))
	}
	if len(vals) != 3*929 {
		fmt.Fprintf(os.Stderr, "got %d values, want %d\n", len(vals), 3*929)
		os.Exit(1)
	}

	bad := 0
	for c := 0; c < 3; c++ {
		seen := map[uint32]bool{}
		for k := 0; k < 929; k++ {
			v := vals[c*929+k]
			runs, ok := runsOf(v)
			if !ok {
				fmt.Fprintf(os.Stderr, "cluster %d cw %d: %#x invalid run structure\n", c, k, v)
				bad++
				continue
			}
			kk := ((runs[0]-runs[2]+runs[4]-runs[6])%9 + 9) % 9
			if kk != c*3 {
				fmt.Fprintf(os.Stderr, "cluster %d cw %d: %#x cluster value %d\n", c, k, v, kk)
				bad++
			}
			if seen[v] {
				fmt.Fprintf(os.Stderr, "cluster %d cw %d: %#x duplicate\n", c, k, v)
				bad++
			}
			seen[v] = true
		}
	}
	if bad > 0 {
		fmt.Fprintf(os.Stderr, "%d problems\n", bad)
		os.Exit(1)
	}
	fmt.Fprintln(os.Stderr, "table OK: 3 clusters x 929, all entries structurally valid and unique")

	fmt.Println("// SPDX-License-Identifier: MIT")
	fmt.Println()
	fmt.Println("// Code generated by tools/genpdf417; DO NOT EDIT.")
	fmt.Println()
	fmt.Println("package asposepdf")
	fmt.Println()
	fmt.Println("// pdf417Codewords is the PDF417 codeword-to-bar-pattern table (ISO/IEC 15438")
	fmt.Println("// Annex A): [cluster][codeword] -> 17 module bits, most significant bit first,")
	fmt.Println("// 1 = bar. Extracted mechanically from the table in ZXing's PDF417.java")
	fmt.Println("// (Apache-2.0; see third_party/PDF417-TABLE-NOTICE.txt), matched against zint's")
	fmt.Println("// independent copy, and structurally verified by the generator and by")
	fmt.Println("// barcode_pdf417_test.go.")
	fmt.Println("var pdf417Codewords = [3][929]uint32{")
	for c := 0; c < 3; c++ {
		fmt.Println("\t{")
		for k := 0; k < 929; k += 8 {
			fmt.Print("\t\t")
			for m := k; m < k+8 && m < 929; m++ {
				fmt.Printf("0x%05x,", vals[c*929+m])
				if m < k+7 && m < 928 {
					fmt.Print(" ")
				}
			}
			fmt.Println()
		}
		fmt.Println("\t},")
	}
	fmt.Println("}")
}

// runsOf splits a 17-bit pattern (MSB first) into its 8 alternating
// bar/space run widths, requiring it to start with a bar and end with a
// space, every run 1..6, total 17.
func runsOf(v uint32) ([8]int, bool) {
	var runs [8]int
	if v>>17 != 0 || (v>>16)&1 != 1 || v&1 != 0 {
		return runs, false
	}
	idx, cur, n := 0, 1, 1
	prev := (v >> 16) & 1
	for b := 15; b >= 0; b-- {
		bit := (v >> uint(b)) & 1
		if bit == prev {
			n++
			continue
		}
		if idx >= 8 || n > 6 {
			return runs, false
		}
		runs[idx] = n
		idx++
		prev, n = bit, 1
		cur++
	}
	if idx != 7 || n > 6 {
		return runs, false
	}
	runs[7] = n
	sum := 0
	for _, r := range runs {
		sum += r
	}
	return runs, sum == 17
}
